### PR TITLE
Fix OOM

### PR DESCRIPTION
**Pull request by robohorse**
- removed bitmaps fields
- now returns null in case of OOM
- now all bitmaps invokes recycler()

### CODE REVIEW

**Comment by veghtomi** [comment]
@robohorse This modification just kills the purpose of this library. Check out the memory consumption of the original shimmer and the one you created. Basically, you create a new `Bitmap` every 16ms with a size of 3 MB depending on the size of the layout.

Memory consumption of your version:
shimmer_modified

Memory consumption of the original version:
original

**Comment by robohorse** [comment]
hmm, but your solution has strong memory leaks,  if we reopen many times similar screens. We tested with QA your solution and crashes occures all time. With this fixes we have no crashes.  I think that there are some problems with livecycle. I will think how to optimize it

**Comment by robohorse** [comment]
also maybe create 2 different bitmaps: background and line with gradient and use android animation utils to translate it without inner bitmap fields?

**Comment by veghtomi** [comment]
Never tried that solution so you can do some experiment

**Pull request closed without merging**
